# Generated by Django 3.2.13 on 2022-08-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_unique_ingredients_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт и ингредиент', 'verbose_name_plural': 'Рецепт и ингредиенты'},
        ),
    ]
